#!/usr/bin/env bash
# Full local release build for TorrServer-LT.
#
# TorrServer-LT links libtorrent (C++) through cgo, so the old pure-Go
# GOOS/GOARCH matrix does not apply: every target needs a cross toolchain and
# a per-target libtorrent build. That work lives in build/<target>.sh (see
# build/README.md); this wrapper only refreshes the embedded web UI and the
# swagger docs, then delegates to build/all.sh.
#
# Supported targets: linux-amd64 linux-arm64 linux-armv7 windows-amd64
#                    android-arm64 android-armv7 darwin-amd64 darwin-arm64
#
# Usage:
#   ./build-all.sh                          # everything the host can build
#   TARGETS="linux-arm64" ./build-all.sh    # a subset
#   TS_VERSION=MatriX.142.LT-1.1.7 ./build-all.sh # stamp a release version
#   SKIP_WEB=1 SKIP_DOCS=1 ./build-all.sh   # binaries only
#
# Binaries land in _out/TorrServer-LT-<target>. The web bundle and swagger
# docs are committed to the repo, so both steps are skipped with a warning
# when their tools (node/npm, swag) are unavailable.

set -euo pipefail

ROOT="$(cd "$(dirname "$0")" && pwd)"
GOBIN=${GOBIN:-go}

$GOBIN version

#### Build web (embedded bundle under web/, regenerated by gen_web.go)
if [[ -z "${SKIP_WEB:-}" ]]; then
  if command -v npm >/dev/null 2>&1; then
    echo "Build web"
    export NODE_OPTIONS=--openssl-legacy-provider
    (cd "$ROOT" && $GOBIN run gen_web.go)
  else
    echo "WARN: npm not found — keeping the committed web bundle (set SKIP_WEB=1 to silence)"
  fi
fi

#### Update api docs
if [[ -z "${SKIP_DOCS:-}" ]]; then
  if $GOBIN install github.com/swaggo/swag/cmd/swag@latest >/dev/null 2>&1; then
    echo "Build docs"
    (cd "$ROOT/server" && "$(go env GOPATH)/bin/swag" init -g web/server.go)
  else
    echo "WARN: swag install failed — keeping the committed swagger docs (set SKIP_DOCS=1 to silence)"
  fi
fi

#### Cross-build all targets (toolchain detection + summary in build/all.sh)
exec "$ROOT/build/all.sh"
